version: "3.9"

services:
  make:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./make/Dockerfile
    volumes:
      - ${SOURCE_FOLDER}:/src:ro
      - ${BUILD_FOLDER}:/build:rw
    environment:
      - PROJECT=${PROJECT_NAME}

  server:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ${SERVER_FOLDER}:/server-files:ro
